version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-airbyte
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: airbyte
      # MYSQL_PASSWORD: airbyte
      # MYSQL_DATABASE: airbyte_db
    ports:
      - "3306:3306"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    networks:
      - airbyte_network

networks:
  airbyte_network:
